import type {
  FindingSeverity,
  ParsedReport,
  ReportFinding,
  SentinelReport,
  ValidationItem,
  ValidationSection,
  ValidationStatus,
} from "./report-types";

const MAX_FILE_BYTES = 2 * 1024 * 1024;

const VALID_STATUSES: ValidationStatus[] = [
  "success",
  "error",
  "warning",
  "info",
  "pending",
];

export class ReportParseError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ReportParseError";
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isValidationStatus(value: unknown): value is ValidationStatus {
  return (
    typeof value === "string" &&
    (VALID_STATUSES as string[]).includes(value)
  );
}

function isValidationItem(value: unknown): value is ValidationItem {
  if (!isRecord(value)) return false;
  return (
    typeof value.title === "string" &&
    isValidationStatus(value.status) &&
    typeof value.message === "string"
  );
}

function isValidationSection(value: unknown): value is ValidationSection {
  if (!isRecord(value)) return false;
  if (typeof value.name !== "string" || !Array.isArray(value.items)) {
    return false;
  }
  return value.items.every(isValidationItem);
}

function isSentinelReport(value: unknown): value is SentinelReport {
  if (!isRecord(value) || !isRecord(value.project)) return false;

  const { project } = value;
  const summary = project.summary;

  if (
    typeof project.name !== "string" ||
    typeof project.scanDate !== "string" ||
    typeof project.scanTime !== "string" ||
    !Array.isArray(project.sections) ||
    !isRecord(summary)
  ) {
    return false;
  }

  if (
    typeof summary.errors !== "number" ||
    typeof summary.warnings !== "number" ||
    typeof summary.info !== "number" ||
    typeof summary.pending !== "number" ||
    typeof summary.healthScore !== "number"
  ) {
    return false;
  }

  return project.sections.every(isValidationSection);
}

function statusToSeverity(status: ValidationStatus): FindingSeverity | null {
  switch (status) {
    case "error":
      return "critical";
    case "warning":
      return "warning";
    case "info":
      return "info";
    default:
      return null;
  }
}

export function computeCoverage(
  sections: ValidationSection[]
): number | null {
  const usageSection = sections.find((s) => s.name === "Function Usage");
  if (!usageSection || usageSection.items.length === 0) return null;

  const total = usageSection.items.length;
  const called = usageSection.items.filter((i) => i.status === "success").length;

  return Math.round((called / total) * 100);
}

function extractFindings(sections: ValidationSection[]): ParsedReport["findings"] {
  const findings: ParsedReport["findings"] = {
    critical: [],
    warning: [],
    info: [],
  };

  for (const section of sections) {
    for (const item of section.items) {
      const severity = statusToSeverity(item.status);
      if (!severity) continue;

      const finding: ReportFinding = {
        title: item.title,
        message: item.message,
        severity,
        section: section.name,
      };

      findings[severity].push(finding);
    }
  }

  return findings;
}

function formatScanTimestamp(scanDate: string, scanTime: string): string {
  const parsed = new Date(scanDate);
  if (!Number.isNaN(parsed.getTime())) {
    return parsed.toLocaleString(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
    });
  }
  return `${scanDate} ${scanTime}`.trim();
}

export function parseReportJson(raw: unknown): ParsedReport {
  if (!isSentinelReport(raw)) {
    throw new ReportParseError(
      "Invalid Sentinel report format. Expected a report.json file generated by the Sentinel CLI."
    );
  }

  const { project } = raw;

  return {
    contractName: project.name,
    scanTimestamp: formatScanTimestamp(project.scanDate, project.scanTime),
    coveragePercent: computeCoverage(project.sections),
    healthScore: project.summary.healthScore,
    summary: project.summary,
    findings: extractFindings(project.sections),
    sections: project.sections,
  };
}

export function parseReportFile(
  file: File
): Promise<{ parsed: ParsedReport; raw: SentinelReport }> {
  if (!file.name.endsWith(".json")) {
    return Promise.reject(
      new ReportParseError("Only .json report files are supported.")
    );
  }

  if (file.size > MAX_FILE_BYTES) {
    return Promise.reject(
      new ReportParseError("Report file exceeds the 2 MB size limit.")
    );
  }

  return file.text().then((text) => {
    let json: unknown;
    try {
      json = JSON.parse(text);
    } catch {
      throw new ReportParseError("File is not valid JSON.");
    }
    const parsed = parseReportJson(json);
    return { parsed, raw: json as SentinelReport };
  });
}

/** Sample report matching CLI output for download / testing */
export function createSampleReport(): SentinelReport {
  return {
    project: {
      name: "Sentinel Scan",
      scanDate: new Date().toISOString(),
      scanTime: new Date().toLocaleTimeString(),
      summary: {
        errors: 1,
        warnings: 2,
        info: 1,
        pending: 0,
        healthScore: 89,
      },
      sections: [
        {
          name: "Project Structure",
          items: [
            { title: "package.json", status: "success", message: "Found" },
            { title: "tsconfig.json", status: "success", message: "Found" },
            { title: ".env", status: "warning", message: ".env is optional but not found" },
          ],
        },
        {
          name: "Environment Validation",
          items: [
            {
              title: "RPC_URL",
              status: "error",
              message: "Missing from .env file",
            },
          ],
        },
        {
          name: "Function Usage",
          items: [
            {
              title: "initialize",
              status: "success",
              message: "Function is used in backend calls",
            },
            {
              title: "transfer",
              status: "success",
              message: "Function is used in backend calls",
            },
            {
              title: "approve",
              status: "warning",
              message: "Function exists in contract but not used in backend calls",
            },
            {
              title: "mint",
              status: "warning",
              message: "Function exists in contract but not used in backend calls",
            },
          ],
        },
      ],
    },
  };
}
